NumPy (Numerical Python) is an open source Python library that’s widely used in science and engineering.

The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray, and a large library of functions that operate efficiently on these data structures.

How to import NumPy

In [4]:
import numpy as np

Reading the example code


In [12]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

In [13]:
a.shape

(2, 3)

NumPy arrays have some restrictions.

    All elements of the array must be of the same type of data.

    Once created, the total size of the the array can’t change.

    The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the 
    same number of columns.

Note

As with built-in Python sequences, NumPy arrays are “0-indexed”: the first element of the array is accessed using index 0, not 1.

In [69]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [15]:
a[0]

1

In [16]:
a[6]

IndexError: index 6 is out of bounds for axis 0 with size 6

In [17]:
a[6] = 7

IndexError: index 6 is out of bounds for axis 0 with size 6

In [18]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

One major difference is that slice indexing of a list copies the elements into a new list, but slicing an array returns a view: an object that refers to the data in the original array. The original array can be mutated using the view.

In [26]:
b = a[3:]
b

array([4, 5, 6])

In [53]:
id(b) == id(a[3:])

False

In [54]:
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

In [47]:
id(b[:]) == id(a[3:])

True

In [48]:
b

array([40,  5,  6])

In [49]:
a[3:]

array([40,  5,  6])

In [51]:
id(b[1]) == id(a[3])

True

In [55]:
id(a[3])

139744147259440

In [58]:
id(b[0])

139744147260688

In [59]:
id(b[1])

139744147261680

In [60]:
id(a[4])

139744147260880

In [62]:
id(b[0]) == id(a[4])

True

When you run this code, you'll find that id(b[0]) == id(a[4]) is True, confirming that b[0] and a[4] share the same memory address because b is a view of a[3:]. because b is a view of a[3:]

In [77]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
a[1, 3]

8

Another difference between an array and a list of lists is that an element of the array can be accessed by specifying the index along each axis within a single set of square brackets, separated by commas. For instance, the element 8 is in row 1 and column 3

Array attributes

This section covers the ndim, shape, size, and dtype attributes of an array.

The number of dimensions of an array is contained in the ndim attribute.

In [82]:
a.ndim

2

The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.

In [87]:
a.shape

(3, 4)

In [88]:
len(a.shape) == a.ndim

True

The fixed, total number of elements in array is contained in the size attribute.

In [99]:
a.size

12

In [100]:
import math
a.size == math.prod(a.shape)

True

Arrays are typically “homogeneous”, meaning that they contain elements of only one “data type”. The data type is recorded in the dtype attribute.

In [111]:
a.dtype

dtype('int64')

How to create a basic array
This section covers np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s

In [114]:
np.zeros(2)

array([0., 0.])

Or an array filled with 1’s

In [118]:
np.ones(2)

array([1., 1.])

even an empty array! The function empty creates an array whose initial content is random and depends on the state of the memory. The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

In [119]:
np.empty(2)

array([1., 1.])

You can create an array with a range of elements

In [125]:
np.arange(4)

array([0, 1, 2, 3])

You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval

In [127]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Adding, removing, and sorting elements

In [131]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [133]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [138]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [135]:
np.concatenate((a, b))a = np.arange(6)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [150]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [160]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

Can you reshape an array?

In [162]:
a = np.arange(6)

In [165]:
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

With np.reshape, you can specify a few optional parameters

In [178]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

How to convert a 1D array into a 2D array (how to add a new axis to an array)

You can use np.newaxis and np.expand_dims to increase the dimensions of your existing array.

In [227]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [228]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

You can use np.newaxis to add a new axis

In [229]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

You can also expand an array by inserting a new axis at a specified position with np.expand_dims

In [292]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [293]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [301]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

Indexing and slicing

In [307]:
data = np.array([1, 2, 3])

In [308]:
data[1]

2

In [309]:
data[0:2]

array([1, 2])

In [310]:
data[1:]

array([2, 3])

In [311]:
data[-2:]

array([2, 3])

In [317]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [319]:
print(a[a < 5])

[1 2 3 4]


In [320]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [321]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [326]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [327]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
